### PR TITLE
Fixes #168 add choice-in-sequence handling

### LINKED ISSUE #168: xs:Choice of xs:Sequence not supported?
Attempting to parse this xsd results in a fatal. Is this an unsupported situation or a bug? Thoughts on a workaround?

https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd

```
<element name="PGPData" type="ds:PGPDataType"/> 
<complexType name="PGPDataType"> 
  <choice>
    <sequence>
      <element name="PGPKeyID" type="base64Binary"/> 
      <element name="PGPKeyPacket" type="base64Binary" minOccurs="0"/> 
      <any namespace="##other" processContents="lax" minOccurs="0"
       maxOccurs="unbounded"/>
    </sequence>
    <sequence>
      <element name="PGPKeyPacket" type="base64Binary"/> 
      <any namespace="##other" processContents="lax" minOccurs="0"
       maxOccurs="unbounded"/>
    </sequence>
  </choice>
</complexType>
```
```
PHP Fatal error:  Uncaught TypeError: GoetasWebservices\Xsd\XsdToPhp\Php\PhpConverter::visitElement(): Argument #3 ($element) must be of type GoetasWebservices\XML\XSDReader\Schema\Element\ElementSingle, GoetasWebservices\XML\XSDReader\Schema\Element\Sequence given, called in ...\vendor\goetas-webservices\xsd2php\src\Php\PhpConverter.php on line 133 and defined in ...\vendor\goetas-webservices\xsd2php\src\Php\PhpConverter.php:429
```

### PR DESCRIPTION
**Pull request by BigBadBassMan**
This fixes #168 with handling for sequences within choices.

also, some basic return types have been added

### CODE REVIEW

File: src/Php/PhpConverter.php [hunk 1]
```diff
@@ -119,34 +119,36 @@ private function visitTypeBase(PHPClass $class, Type $type)
...
 	 * @param Schema $schema
 	 * @param Sequence $sequence
 	 */
-	private function visitSequence(PHPClass $class, Schema $schema, Sequence $sequence)
-	{
+	private function visitSequence(PHPClass $class, Schema $schema, Sequence $sequence): void
+    {
 		foreach ($sequence->getElements() as $childSequence) {
-			if ($childSequence instanceof Group) {
+            if ($childSequence instanceof Group) {
```
Comment (goetas) [inline src/Php/PhpConverter.php:133]: indentation seems weird...

Comment (BigBadBassMan) [reply src/Php/PhpConverter.php:133]: Why, I don't see anything wrong with it - shows as exactly the same indent as before?
Or were there spaces _and_ tabs used before?

Comment (BigBadBassMan) [reply src/Php/PhpConverter.php:133]: yeah, there where mixed spaces and tab indents before, I converted all to spaces now. as it should be.
I could do a separate PR to introduce PHPCS or PHP-CS-Fixer to prevent this in the future, if you want.

**Comment by goetas** [comment]
@BigBadBassMan thanks a lot for addressing my comment. I do not see any tests checking your changes. Could you please test the feature/fix you have implemented?

**Comment by BigBadBassMan** [comment]
Hi @goetas sorry for the delay, I added a minimal testcase that should reflect the changes. (Hopefully at least, testing this is not so straight forward ...) Would that be sufficient?
